version: "3.8"
services:
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - front
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  db:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  front:
    build:
      context: ../front_crm
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192

volumes:
  db:
