version: '3.8'
services:
  server:
    build: .
    ports:
      - "5000:${PORT}"
    depends_on:
      - db
      - front
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  db:
    container_name: postgres
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - db:/data/db
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot

  front:
    build: ../front_crm
    ports:
      - "80:80"

volumes:
  db:
