version: "1.0"

services:

  web:
    image: server
    container_name: server_api
    build: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  db:
    container_name: postgres
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  react-app:
    build:
      context: ../front
    ports:
      - "80:80"

volumes:
  db: {}
